
export enum TableColumnEnum {
    TOGGLE_BUTTON = 'toggle',
    DELETE_BUTTON = 'delete_Btn',

    NORMAL = 'normal',
    IMAGE = 'image',
    MULTIPLEIMAGES='multiple_images',
    MULTIPLEIMAGESINCOLUMN='multiple_images_in_column',
    CASH_REGISTER = 'cash-register',
    COMBINED_COLUMN='combined_column',
    CURRENCY_SYMBOL='currency_symbol',
    BALANCE_COLUMN='balance_column',
    REMARKS='remarks',
    DATE_FORMAT = 'date_format',
    DATE_ONLY='date_only',
    Narration='narration',
    FileUpload='fileupload',

    REDIRECTION_COLUMN='redirection_column',
    ORDER_TYPE='order_type',
    REDIRECTION_COLUMN_2='redirection_column_2',
    LOCATION_CHECK='location_check',
    ATTACHMENT ='attachment',
    CHECKBOX_COLUMN='checkbox_column',
    CHECKBOX_SINGLE_SELECTION_COLUMN = 'checkbox_single_selection_column',
    LOCATION_ROWS='location_rows',
    PRINT_STATUS='print_status',
    PAYMENT_STATUS='payment_status',
    EXPORT_COLUMN='export_column',
    MULTIPLEATTACHMENT ='multiple_attachment',
    SALEPRINTING_BUTTON = 'sale_printing_button',
    CONVERTED_TO_SALE='converted_to_sale',

}