export enum CustomerPermissionEnum {
    SubMenuViewCustomers = 'Sub Menu_View Customers',
    SubMenuCustomersAccounts = 'Sub Menu_Customers Accounts',
    SubMenuAddressReport = 'Sub Menu_Address Report',
    CustomerLedgers = 'Customer Ledgers',
    AddClient = 'Add Client',
    ClientsListing = 'Clients Listing',
    UpdateClient = 'Update Client',
    ClientLeadger = 'Client Leadger',
    CustomerListing = 'Customer Listing',
    BlackListedCustomerListing = 'Blacklisted Customer Listing',
    CustomerPayments = 'Customer Payments',
    CustomerDiscountListing = 'Customer Discount Listing',
    CustomerProductDiscount = 'Customer Product Discount',
    // AddMultipleCustomer='Add Multiple Customer',
    DirectPayment='Direct Payment',
    AddBalance='Add Balance',
    ReversePayment='Reverse Payment',
    CustomerPaymentDetails='Customer Payment Details',

    ClearDirectPayment='Clear Direct Payment',
}