export enum PurchasePermissionEnum {
    AddPurchase = 'Add Purchase',
    AddBackOrder = 'Add Back Order',
    
    ReturnPurchaseHistory = 'Return Purchase History',
    PurchaseListing = 'Purchases Listing',
    PurchaseRefund = 'Purchase Refund',
    SubMenuPurchaseOverview = 'Sub Menu_Purchases Overview',
    SubMenuReturnPurchase ='Sub Menu_Return Purchases',
    SubMenuBackOrderOverview= 'Sub Menu_Back Order Overview',
    BackOrder = 'Back Order',
    PurchasePriceColumn = 'Purchase Price Column',
    PaidAmountColumn = 'Paid Amount Column',
    PurchaseInvoicePrint = 'Purchase Invoice Print',
    SubMenuOpenPurchaseOrder ='Sub Menu Pre Order',
    OpenPurchaseOrderReport='Pre Order Report',
    SubMenuCustomizedOpenPurchaseOrder ='Sub Menu Customized Pre Order',
    CustomizedOpenPurchaseOrderReport='Pre Order Customized Report',
    AddOpenPurchaseOrder='Add Pre Order',
    PurchaseCustomizedListing='Purchases Customized Listing',
    SubMenuPurchaseCustomizedOverview = 'Sub Menu_Purchases Customized Overview',
    CurrentBalanceColumninPurchaseCreate = 'Current Balance Column in Purchase Create',
    CurrentBalanceColumninBackOrderCreate='Current Balance Column in Back Order Create',
    CurrentBalanceColumninPre_OrderCreate = 'Current Balance Column in Pre-Order Create',
    AddHoldPurchase = 'Add Hold Purchase',
    HoldPurchaseReport='Hold Purchase Report',
    UpdateHoldPurchase = 'Update Hold Purchase',
    SubMenuHoldPurchase ='Sub Menu Hold Purchase',

  }