export enum SalesPermissionEnum {
    SubMenuInvoiceOverview = 'Sub Menu_Invoice Overview',
    SubMenuCreditNote = 'Sub Menu_Credit Note',
    SubMenuProformaInvoiceOverview = 'Sub Menu_Proforma InvoiceOverview',
    SubMenuProforma = 'Sub Menu_Proforma',
    PerfomaSaleListing = 'Perfoma Sale Listing',
    SubMenuHoldSale = 'Sub Menu_Hold Sale',
    SubMenuStats = 'Sub Menu_Stats',
    SubMenuOverviewProductWise ='Sub Menu_Overview Product Wise',
    SubMenuOverviewUserWise= 'Sub Menu_Overview User Wise',
    SubMenuOverviewSubCategoryWise = 'Sub Menu_Overview Sub Category Wise',
    AddSale ='Add Sale',
    AddSaleByExternalIncomingOrder ='Add Sale By External Incoming Order',
    DeleteExternalIncomingOrder ='Delete External Incoming Order',

    AddHoldSale = 'Add Hold Sale',
    OpenSalesListing ='Open Sales Listing',
    AddPerformaInvoice ='Add Performa Invoice',
    DeletePerfomaInvoice = 'Delete Perfoma Invoice',
    SalesHistory = 'Sales History',
    SubMenuSaleInvoicesOverview = 'Sub Menu_Sale Invoices Overview',
    ReturnSalesHistory = 'Return Sales History',
    SaleRefund = 'Sale Refund',
    AddPerfomaInvoice = 'Add Perfoma Invoice',
    TotalAmountColumn ='Total Amount Column',
   
    PreviousInvoicesinSaleCreate='Previous Invoices in Sale Create',
    PreviousBalanceinSaleCreate='Previous Balance in Sale Create',
    CurrentBalanceinSaleCreate='Current Balance in Sale Create',
    CurrentBalanceinSaleDetails = 'Current Balance in Sale Details',
    CurrentBalanceinHoldSaleDetails = 'Current Balance in Hold Sale Details',
    CurrentBalanceinRefundSaleDetails = 'Current Balance in Refund Sale Details',
    PreviousInvoicesinProformaCreate= 'Previous Invoices in Proforma Create',
    PreviousBalanceinProformaCreate = 'Previous Balance in Proforma Create',  
    CurrentBalanceinProformaCreate = 'Current Balance in Proforma Create',
    CurrentBalanceColumninProformaCreate='Current Balance Column in Proforma Create',
    CurrentBalanceinProformaDetails='Current Balance in Proforma Details',
    CurrentBalanceinVPOrderDetails='Current Balance in VP Order Details',
    CurrentBalanceColumninSaleCreate ='Current Balance Column in Sale Create',
    AmountAndPaymentColumninSaleOverview ='Amount And Payment Column in Sale Overview',
  }