import { ClientAddressModel } from "./ClientAddressModel";
import { AddressDetailModel } from "./AddressDetailModel";
import { ClientContactModel } from "./ClientContactModel";

export class ClientModel {
    public Address: string ;
        public BankAccountDescription: string ;
        public BankAccountNo: string ;
        public BICCode: string ;
        public City: string ;
        public CityID?: number ;
        public ClientAddresses: ClientAddressModel[] ;
        public ClientAddressesDetail: AddressDetailModel[] ;
        public ClientContacts: ClientContactModel[] ;
        public ClientID: number ;
        public ClientSource: string ;
        public ClientSourceID?: number ;
        public CountryID?: number ;
        public CreatedAtForClient?: string ;
        public CreatedByUserIDForClient?: number ;
        public Customer: string ;
        public dCreditLimit?: number ;
        public dOpeningBalance?: number ;
        public EmailAddress: string ;
        public FirstName: string ;
        public Image: string ;
        public IsActiveForClient?: boolean ;
        public IsCustomer?: boolean ;
        public IsSupplier?: boolean ;
        public LastName: string ;
        public Mobile: string ;
        public PaymentPermission: string ;
        public PhoneNo: string ;
        public PostalCode: string ;
        public PostCode: string ;
        public sCityName: string ;
        public sCompanyName: string ;
        public sCountryName: string ;
        public sFax: string ;
        public ShippingMethod: string ;
        public ShippingMethodID?: number ;
        public sRemarks: string ;
        public sSalesTax: string ;
        public State: string ;
        public StateID?: number ;
        public sTaxNo: string ;
        public StreetAddress: string ;
        public Supplier: string ;
        public UpdatedAtForClient?: string ;
        public UpdatePermission: string ;
        public VATNumber: string ;
        public Website: string ;
}